"""add trainers table

Revision ID: 5bd70ff0893d
Revises: f2845c54fc6d
Create Date: 2026-08-15 13:02:37.799419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd70ff0893d'
down_revision: Union[str, Sequence[str], None] = 'f2845c54fc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainers_phone'), 'trainers', ['phone'], unique=False)
    op.create_index(op.f('ix_trainers_trainer_code'), 'trainers', ['trainer_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainers_trainer_code'), table_name='trainers')
    op.drop_index(op.f('ix_trainers_phone'), table_name='trainers')
    op.drop_table('trainers')
    # ### end Alembic commands ###
